### ISSUE TITLE
Bug - Player invisible/not loaded

### ISSUE THREAD

**Issue by Chungoosy** [PolyMarsDev/Sokobot#6]
This happened while on level 4, where the player emoji never showed up. After moving the character, the emoji would re-appear.
Edit: This only happens if the player spawns on the same block as a X
![image](https://user-images.githubusercontent.com/68400452/89115197-3fb15780-d43a-11ea-9aa9-20de9fd72d26.png)

**Comment by dzlandis** [comment]
This happened to me on the first level since they are randomly generated. Pressing wasd or clicking the emoji's brought the character back into the game. I am wondering if this is intentional to give you a preview of the area before you officially start the level.

**Comment by dzlandis** [comment]
This is still an active bug.
![Screenshot from 2020-08-06 13-07-49](https://user-images.githubusercontent.com/49926644/89578192-a346d680-d7e6-11ea-9ac6-eda7b66b9448.png)

**Comment by dzlandis** [comment]
Spamming commands quickly enough using WASD can cause the player to move into a block instead of push it. This usually happens when trying to push a block into an X.
![Screenshot from 2020-08-06 14-26-07](https://user-images.githubusercontent.com/49926644/89584378-d55d3600-d7f0-11ea-9392-77d75a65e926.png)

**Comment by AffluentAvo** [comment]
This bug was fixed in a previous update

**Comment by AffluentAvo** [comment]
Closing as bug was fixed.
